### PR TITLE
Fixed memory leaks in Channels

### PR DESCRIPTION
**Pull request by codeOfRobin**

### CODE REVIEW

**Comment by codeOfRobin** [comment]
I've also changed the URL so it'd work with the [official chat example server](https://github.com/chrismccord/phoenix_chat_example)

**Comment by sjrmanning** [comment]
Thanks for this! I've been travelling in between working, so haven't had much time lately but I'll try take a look at this early this week :) Really appreciate your efforts!

**Comment by codeOfRobin** [comment]
No problem @sjrmanning ! BTW, you might wanna check out your twitter DMs.

**Comment by sjrmanning** [comment]
Thanks Robin! Sorry it took a while to get around to looking at this. Really appreciate your efforts 👍

**Pull request merged**
